version: '3.4'

services:
  discountapi:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Dockerfile

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4  

volumes:
  postgres_data:
  pgadmin_data: